Repository bcgov/spring-boot-starters, pull requests merged in 2020-08, with the labels that each got.

#8 Create maven-test.yaml
  .github/workflows/maven-test.yaml
Labels: ci/cd, git action

#12 Adding bceid lib
  src/pom.xml
  src/spring-bceid-starter/README.md
  src/spring-bceid-starter/pom.xml
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/AutoConfiguration.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/BCeIdProperties.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/BCeIDAccountService.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/BCeIDAccountServiceImpl.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/GetAccountRequest.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/mappers/AccountDetailRequestMapper.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/mappers/AddressMapper.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/mappers/BCeIdMapper.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/mappers/IndividualIdentityMapper.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/mappers/NameMapper.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/models/Address.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/models/IndividualIdentity.java
  src/spring-bceid-starter/src/main/java/ca/bc/gov/open/bceid/starter/account/models/Name.java
  src/spring-bceid-starter/src/main/resources/META-INF/spring.factories
  src/spring-bceid-starter/src/main/resources/wsdl/BCeIDService.wsdl
  src/spring-bceid-starter/src/test/java/ca/bc/gov/open/bceid/starter/AutoConfigurationTest.java
  src/spring-bceid-starter/src/test/java/ca/bc/gov/open/bceid/starter/account/BCeIDAccountServiceImplTest.java
  src/spring-bceid-starter/src/test/java/ca/bc/gov/open/bceid/starter/account/GetAccountRequestTest.java
  src/spring-sftp-starter/pom.xml
  src/spring-starters-bom/pom.xml
Labels: TEAMWORK! (⌐■_■)

#20 Integration notes
  README.md
Labels: documentation

#21 Fix order bug
  src/bambora-payment-starter/src/main/java/ca/bc/gov/open/bambora/payment/starter/managment/BamboraCardServiceImpl.java
  src/bambora-payment-starter/src/test/java/ca/bc/gov/open/bambora/payment/starter/managment/BamboraCardServiceImplTest.java
Labels: bug
